Added USSR anthem and the Cheese song as new discs
DaRealTurtyWurty/CommunityMod pull request #25
Opened 2021-08-18 21:10 UTC by JustCallMeRandom

2021-08-18 22:38 UTC, DaRealTurtyWurty approved these changes

2021-08-18 22:39 UTC, DaRealTurtyWurty requested changes
Add to README.md

2021-08-18 22:39 UTC, JustCallMeRandom commented
oh eyah sorry i keep forgetting to do that :P

2021-08-19 17:44 UTC, DaRealTurtyWurty approved these changes

2021-08-19 17:48 UTC, merged