Add a description to the README.md
DaRealTurtyWurty/CommunityMod pull request #35
Opened 2021-08-20 14:06 UTC by MaroonShaded

I've also edited some steps.
Intellij says it cleaned up imports so yeah, I guess that too

2021-08-20 14:16 UTC, DaRealTurtyWurty requested changes

2021-08-20 14:16 UTC, DaRealTurtyWurty commented on src/main/java/io/github/communitymod/CommunityMod.java
> +import io.github.communitymod.core.init.*;
Don't do this. Wildcard imports should be avoided.

2021-08-20 14:16 UTC, DaRealTurtyWurty commented on src/main/java/io/github/communitymod/common/entities/BeanEntity.java
> +import net.minecraft.world.entity.ai.goal.*;
Don't do this. Wildcard imports should be avoided.

2021-08-20 14:16 UTC, DaRealTurtyWurty commented on src/main/java/io/github/communitymod/common/entities/GooseEntity.java
> +import net.minecraft.world.entity.ai.goal.*;
Don't do this. Wildcard imports should be avoided.

2021-08-20 14:16 UTC, DaRealTurtyWurty commented on src/main/java/io/github/communitymod/core/init/ItemInit.java
> +import net.minecraft.world.item.*;
Don't do this. Wildcard imports should be avoided.

2021-08-20 14:16 UTC, DaRealTurtyWurty commented on src/main/java/io/github/communitymod/core/init/ItemInit.java
> +import io.github.communitymod.common.items.*;
Don't do this. Wildcard imports should be avoided.

2021-08-20 14:16 UTC, DaRealTurtyWurty commented on src/main/java/io/github/communitymod/core/util/SpawnEggData.java
> +import java.awt.*;
Don't do this. Wildcard imports should be avoided.

2021-08-20 20:19 UTC, MaroonShaded commented
I know, I don't like them either, but intellij. aaaa I'll try and remove

2021-08-20 20:42 UTC, MetalTurtle18 commented
> I know, I don't like them either, but intellij. aaaa I'll try and remove

Preferences>editor>code style>java>imports>Class count to import with '*' set to some high number.

2021-08-21 18:57 UTC, DaRealTurtyWurty approved these changes

2021-08-21 18:58 UTC, merged